### ISSUE TITLE
[info] Opinionned comparison of darkThreading vs. OmniThreadLibrary

### ISSUE THREAD

**Issue by edwinyzh** [chapmanworld/DarkGlass#6]
The [original post is here](https://plus.google.com/+EdwinYipAtInnovationGear/posts/53dircwYpxR).
I spent half of my time today to do the comparison so I thought I'd re-post it here for people who need such info:
-------------------------------------
Simple Comparison of OmniThreadLibrary and darkThreading (http://chapmanworld.com/2018/05/24/a-new-mutlti-threading-library-for-delphi-darkthreading/)

I spent half of my time today to dig into darkThreading.

Why?
===
I'm refactoring the multi-thread part of a program, decided to make it as much **FPC-ready** as possible.
Note, OTL is a very good and versatile threading library for Delphi, if the mentioned program would always stick with Windows I won't consider switch ATM.

Observations
===
- like OTL, darkThreading has an **lockless** **inter-thread communication** module that supports multi-sender-one-receiver mode which is just what I need. Actually an 
inter-thread communication channel is my main (of not only) reason to use a 3rd party threading library.
- As opposed to OTL's inter-thread communication module's implemented using Windows messaging, the one in darkThreading's implemented using array thus is more **crossplatform-friendly** 
- By browsing the source code, one can find that darkThreading is designed with cross-platform in mind.
- darkThreading's source code is much small in size and much easy to read and easy to understand.
- darkThreading's very very well and **completely commented** in the source code thus it's very easy to consult the docs while coding, whereas with OTL I need to read the PDF book by pj (don't get me wrong, I was very willing to pay for the book).
- darkThreading's recent github commits shows that it's progress for FPC support. Even if the developer doesn't do that, its 'interface for everything' design makes it very easy for one to add FPC support IMHO.

That's all for now and I'll experiment the code later on.

**Comment by chapmanworld** [comment]
Thank you for the review.
I'd not even considered comparing darkThreading to other threading libraries until I read your comments. My intended use case for the library is to provide the multi-threaded functionality required for darkGlass only, and it's limited functionality is a reflection of that.  None-the-less, it's great to hear that this library has been of use to you and I appreciate the feedback.
